
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  database: foodorderingapp_development
  username: user
  password: test123
  encoding: unicode
  host: localhost
  pool: 5
test:
  adapter: postgresql
  database: foodorderingapp_test
  username: user
  password: test123
  encoding: unicode
  host: localhost
  pool: 5
